language: cpp
arch:
  - amd64
  - ppc64le
os:
  - linux

compiler:
  - gcc
  - clang


before_install:
  - sudo apt-get update
  - sudo apt-get -y install libx11-dev libxi-dev libxtst-dev

script:
  - make
